version: "2"
services:
  palindrome: 
    image: ckvineethchandran/palindrome:latest3
    ports: 
      - 80:8082
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:docker@db:5432/postgres
      - PORT=3000   
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
    volumes:
      - ${PWD}/../:/docker-entrypoint-initdb.d/